version: "3.5"

services:
    app:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./:/app:rw

    queue-server:
        volumes:
            - .docker/beanstalkd/data:/var/lib/beanstalkd